on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            src
            !src/**/*.md

  download:
    runs-on: ubuntu-latest
    environment: dev
    needs: test
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download artifact from test job
        uses: actions/download-artifact@v4
        with:
          name: dist-without-markdown
          path: download
        
      - name: Add dummy file if not exists
        run: |
          if [ ! -f download/abc.txt ]; then
            echo "This is a dummy file" > download/abc.txt
          fi

      - name: Commit and push abc.txt to the repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add download/abc.txt
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Add dummy file abc.txt"
            git push origin HEAD:main
          fi
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown_new
          path: download