on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-without-markdown
          path: |
            src
            !src/**/*.md

  download:
    runs-on: ubuntu-latest
    environment: dev
    needs: test
    steps:
      - name: Download artifact from test job
        uses: actions/download-artifact@v4
        with:
          name: dist-without-markdown
          path: download