on: 
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
  GenerateInitialROCRATE:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        
      - name: Upload ro-crate artifacts
        uses: actions/upload-artifact@v4
        with:
          name: inital-ro-crate
          path: |
            bagit
            !src/**/*.md

  ValidateROCRATE:
    runs-on: ubuntu-latest
    environment: InitialApprovalGate
    needs: GenerateInitialROCRATE
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: inital-ro-crate
          path: download
        
      - name: Add dummy file if not exists
        run: |
          if [ ! -f download/abc.txt ]; then
            echo "This is a dummy file" > download/validated.txt
          fi
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: validated-ro-crate
          path: download

  Workflow-Retrieval:
    runs-on: ubuntu-latest
    needs: ValidateROCRATE
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: validated-ro-crate
          path: download
        
      - name: Add dummy file if not exists
        run: |
          if [ ! -f download/abc.txt ]; then
            echo "This is a dummy file" > download/validated-ro-crate.txt
          fi
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: enriched-ro-crate
          path: download

  SignOff:
    runs-on: ubuntu-latest
    environment: SignOff
    needs: Workflow-Retrieval

  Workflow-Execution:
    runs-on: ubuntu-latest
    needs: SignOff
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: enriched-ro-crate
          path: download
        
      - name: Simulate adding the data
        run: |
          if [ ! -f download/abc.txt ]; then
            echo "This is a dummy file" > download/data.txt
          fi
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packaged-ro-crate
          path: download

  Disclosure:
    runs-on: ubuntu-latest
    needs: Workflow-Execution
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packaged-ro-crate
          path: download
        
      - name: Simulate adding the data
        run: |
          if [ ! -f download/abc.txt ]; then
            echo "This is a dummy file" > download/published-ro-crate.txt
          fi
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-ro-crate
          path: download